version: '3.8'

services:
  stamprally:
    build: 
      context: .
      dockerfile: local.Dockerfile
      target: dev
    stdin_open: true
    tty: true
    ports:
      - "8000:8080"
    volumes:
      - ./src:/app/src